services:
  web:
    build:
      context: ..
      dockerfile: service-provider/Dockerfile.dev
    container_name: service-provider-web
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/app
    expose:
      - "3001"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
    extra_hosts:
      - "id-provider.local:host-gateway"
      - "service-provider.local:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: service-provider-nginx
    ports:
      - "3444:443"
    volumes:
      - ../ssl/id-provider.local+1.pem:/etc/nginx/ssl/server.crt:ro
      - ../ssl/id-provider.local+1-key.pem:/etc/nginx/ssl/server.key:ro
      - ./nginx/service-provider.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    extra_hosts:
      - "id-provider.local:host-gateway"
      - "service-provider.local:host-gateway"