services:
  web:
    build:
      context: ../..
      dockerfile: service-provider/membership/Dockerfile.dev
    container_name: membership-web
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3002 -b '0.0.0.0'"
    volumes:
      - .:/app
    expose:
      - "3002"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
    networks:
      - default
      - id-provider_default
    extra_hosts:
      - "id-provider.local:host-gateway"
      - "membership.local:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: membership-nginx
    ports:
      - "3445:443"
    volumes:
      - ../../ssl/id-provider.local+1.pem:/etc/nginx/ssl/server.crt:ro
      - ../../ssl/id-provider.local+1-key.pem:/etc/nginx/ssl/server.key:ro
      - ./nginx/membership.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    extra_hosts:
      - "id-provider.local:host-gateway"
      - "membership.local:host-gateway"

networks:
  id-provider_default:
    external: true
